/**
 * FinTrack Pro — Countries Dataset
 * 195 countries with flag emojis, currency, currencySymbol, and locale.
 */

export const COUNTRIES = [
  { name: 'Afghanistan', code: 'AF', flag: '🇦🇫', currency: 'AFN', currencySymbol: '؋', locale: 'fa-AF' },
  { name: 'Albania', code: 'AL', flag: '🇦🇱', currency: 'ALL', currencySymbol: 'L', locale: 'sq-AL' },
  { name: 'Algeria', code: 'DZ', flag: '🇩🇿', currency: 'DZD', currencySymbol: 'د.ج', locale: 'ar-DZ' },
  { name: 'Andorra', code: 'AD', flag: '🇦🇩', currency: 'EUR', currencySymbol: '€', locale: 'ca-AD' },
  { name: 'Angola', code: 'AO', flag: '🇦🇴', currency: 'AOA', currencySymbol: 'Kz', locale: 'pt-AO' },
  { name: 'Antigua and Barbuda', code: 'AG', flag: '🇦🇬', currency: 'XCD', currencySymbol: '$', locale: 'en-AG' },
  { name: 'Argentina', code: 'AR', flag: '🇦🇷', currency: 'ARS', currencySymbol: '$', locale: 'es-AR' },
  { name: 'Armenia', code: 'AM', flag: '🇦🇲', currency: 'AMD', currencySymbol: '֏', locale: 'hy-AM' },
  { name: 'Australia', code: 'AU', flag: '🇦🇺', currency: 'AUD', currencySymbol: 'A$', locale: 'en-AU' },
  { name: 'Austria', code: 'AT', flag: '🇦🇹', currency: 'EUR', currencySymbol: '€', locale: 'de-AT' },
  { name: 'Azerbaijan', code: 'AZ', flag: '🇦🇿', currency: 'AZN', currencySymbol: '₼', locale: 'az-AZ' },
  { name: 'Bahamas', code: 'BS', flag: '🇧🇸', currency: 'BSD', currencySymbol: '$', locale: 'en-BS' },
  { name: 'Bahrain', code: 'BH', flag: '🇧🇭', currency: 'BHD', currencySymbol: '.د.ب', locale: 'ar-BH' },
  { name: 'Bangladesh', code: 'BD', flag: '🇧🇩', currency: 'BDT', currencySymbol: '৳', locale: 'bn-BD' },
  { name: 'Barbados', code: 'BB', flag: '🇧🇧', currency: 'BBD', currencySymbol: '$', locale: 'en-BB' },
  { name: 'Belarus', code: 'BY', flag: '🇧🇾', currency: 'BYN', currencySymbol: 'Br', locale: 'be-BY' },
  { name: 'Belgium', code: 'BE', flag: '🇧🇪', currency: 'EUR', currencySymbol: '€', locale: 'nl-BE' },
  { name: 'Belize', code: 'BZ', flag: '🇧🇿', currency: 'BZD', currencySymbol: 'BZ$', locale: 'en-BZ' },
  { name: 'Benin', code: 'BJ', flag: '🇧🇯', currency: 'XOF', currencySymbol: 'CFA', locale: 'fr-BJ' },
  { name: 'Bhutan', code: 'BT', flag: '🇧🇹', currency: 'BTN', currencySymbol: 'Nu', locale: 'dz-BT' },
  { name: 'Bolivia', code: 'BO', flag: '🇧🇴', currency: 'BOB', currencySymbol: 'Bs.', locale: 'es-BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA', flag: '🇧🇦', currency: 'BAM', currencySymbol: 'KM', locale: 'bs-BA' },
  { name: 'Botswana', code: 'BW', flag: '🇧🇼', currency: 'BWP', currencySymbol: 'P', locale: 'en-BW' },
  { name: 'Brazil', code: 'BR', flag: '🇧🇷', currency: 'BRL', currencySymbol: 'R$', locale: 'pt-BR' },
  { name: 'Brunei', code: 'BN', flag: '🇧🇳', currency: 'BND', currencySymbol: '$', locale: 'ms-BN' },
  { name: 'Bulgaria', code: 'BG', flag: '🇧🇬', currency: 'BGN', currencySymbol: 'лв', locale: 'bg-BG' },
  { name: 'Burkina Faso', code: 'BF', flag: '🇧🇫', currency: 'XOF', currencySymbol: 'CFA', locale: 'fr-BF' },
  { name: 'Burundi', code: 'BI', flag: '🇧🇮', currency: 'BIF', currencySymbol: 'Fr', locale: 'fr-BI' },
  { name: 'Cabo Verde', code: 'CV', flag: '🇨🇻', currency: 'CVE', currencySymbol: '$', locale: 'pt-CV' },
  { name: 'Cambodia', code: 'KH', flag: '🇰🇭', currency: 'KHR', currencySymbol: '៛', locale: 'km-KH' },
  { name: 'Cameroon', code: 'CM', flag: '🇨🇲', currency: 'XAF', currencySymbol: 'FCFA', locale: 'fr-CM' },
  { name: 'Canada', code: 'CA', flag: '🇨🇦', currency: 'CAD', currencySymbol: 'C$', locale: 'en-CA' },
  { name: 'Central African Republic', code: 'CF', flag: '🇨🇫', currency: 'XAF', currencySymbol: 'FCFA', locale: 'fr-CF' },
  { name: 'Chad', code: 'TD', flag: '🇹🇩', currency: 'XAF', currencySymbol: 'FCFA', locale: 'fr-TD' },
  { name: 'Chile', code: 'CL', flag: '🇨🇱', currency: 'CLP', currencySymbol: '$', locale: 'es-CL' },
  { name: 'China', code: 'CN', flag: '🇨🇳', currency: 'CNY', currencySymbol: '¥', locale: 'zh-CN' },
  { name: 'Colombia', code: 'CO', flag: '🇨🇴', currency: 'COP', currencySymbol: '$', locale: 'es-CO' },
  { name: 'Comoros', code: 'KM', flag: '🇰🇲', currency: 'KMF', currencySymbol: 'Fr', locale: 'ar-KM' },
  { name: 'Congo (Brazzaville)', code: 'CG', flag: '🇨🇬', currency: 'XAF', currencySymbol: 'FCFA', locale: 'fr-CG' },
  { name: 'Congo (DRC)', code: 'CD', flag: '🇨🇩', currency: 'CDF', currencySymbol: 'Fr', locale: 'fr-CD' },
  { name: 'Costa Rica', code: 'CR', flag: '🇨🇷', currency: 'CRC', currencySymbol: '₡', locale: 'es-CR' },
  { name: 'Croatia', code: 'HR', flag: '🇭🇷', currency: 'EUR', currencySymbol: '€', locale: 'hr-HR' },
  { name: 'Cuba', code: 'CU', flag: '🇨🇺', currency: 'CUP', currencySymbol: '$', locale: 'es-CU' },
  { name: 'Cyprus', code: 'CY', flag: '🇨🇾', currency: 'EUR', currencySymbol: '€', locale: 'el-CY' },
  { name: 'Czech Republic', code: 'CZ', flag: '🇨🇿', currency: 'CZK', currencySymbol: 'Kč', locale: 'cs-CZ' },
  { name: 'Denmark', code: 'DK', flag: '🇩🇰', currency: 'DKK', currencySymbol: 'kr', locale: 'da-DK' },
  { name: 'Djibouti', code: 'DJ', flag: '🇩🇯', currency: 'DJF', currencySymbol: 'Fr', locale: 'fr-DJ' },
  { name: 'Dominica', code: 'DM', flag: '🇩🇲', currency: 'XCD', currencySymbol: '$', locale: 'en-DM' },
  { name: 'Dominican Republic', code: 'DO', flag: '🇩🇴', currency: 'DOP', currencySymbol: 'RD$', locale: 'es-DO' },
  { name: 'Ecuador', code: 'EC', flag: '🇪🇨', currency: 'USD', currencySymbol: '$', locale: 'es-EC' },
  { name: 'Egypt', code: 'EG', flag: '🇪🇬', currency: 'EGP', currencySymbol: 'E£', locale: 'ar-EG' },
  { name: 'El Salvador', code: 'SV', flag: '🇸🇻', currency: 'USD', currencySymbol: '$', locale: 'es-SV' },
  { name: 'Equatorial Guinea', code: 'GQ', flag: '🇬🇶', currency: 'XAF', currencySymbol: 'FCFA', locale: 'es-GQ' },
  { name: 'Eritrea', code: 'ER', flag: '🇪🇷', currency: 'ERN', currencySymbol: 'Nfk', locale: 'ti-ER' },
  { name: 'Estonia', code: 'EE', flag: '🇪🇪', currency: 'EUR', currencySymbol: '€', locale: 'et-EE' },
  { name: 'Eswatini', code: 'SZ', flag: '🇸🇿', currency: 'SZL', currencySymbol: 'L', locale: 'en-SZ' },
  { name: 'Ethiopia', code: 'ET', flag: '🇪🇹', currency: 'ETB', currencySymbol: 'Br', locale: 'am-ET' },
  { name: 'Fiji', code: 'FJ', flag: '🇫🇯', currency: 'FJD', currencySymbol: '$', locale: 'en-FJ' },
  { name: 'Finland', code: 'FI', flag: '🇫🇮', currency: 'EUR', currencySymbol: '€', locale: 'fi-FI' },
  { name: 'France', code: 'FR', flag: '🇫🇷', currency: 'EUR', currencySymbol: '€', locale: 'fr-FR' },
  { name: 'Gabon', code: 'GA', flag: '🇬🇦', currency: 'XAF', currencySymbol: 'FCFA', locale: 'fr-GA' },
  { name: 'Gambia', code: 'GM', flag: '🇬🇲', currency: 'GMD', currencySymbol: 'D', locale: 'en-GM' },
  { name: 'Georgia', code: 'GE', flag: '🇬🇪', currency: 'GEL', currencySymbol: '₾', locale: 'ka-GE' },
  { name: 'Germany', code: 'DE', flag: '🇩🇪', currency: 'EUR', currencySymbol: '€', locale: 'de-DE' },
  { name: 'Ghana', code: 'GH', flag: '🇬🇭', currency: 'GHS', currencySymbol: '₵', locale: 'en-GH' },
  { name: 'Greece', code: 'GR', flag: '🇬🇷', currency: 'EUR', currencySymbol: '€', locale: 'el-GR' },
  { name: 'Grenada', code: 'GD', flag: '🇬🇩', currency: 'XCD', currencySymbol: '$', locale: 'en-GD' },
  { name: 'Guatemala', code: 'GT', flag: '🇬🇹', currency: 'GTQ', currencySymbol: 'Q', locale: 'es-GT' },
  { name: 'Guinea', code: 'GN', flag: '🇬🇳', currency: 'GNF', currencySymbol: 'Fr', locale: 'fr-GN' },
  { name: 'Guinea-Bissau', code: 'GW', flag: '🇬🇼', currency: 'XOF', currencySymbol: 'CFA', locale: 'pt-GW' },
  { name: 'Guyana', code: 'GY', flag: '🇬🇾', currency: 'GYD', currencySymbol: '$', locale: 'en-GY' },
  { name: 'Haiti', code: 'HT', flag: '🇭🇹', currency: 'HTG', currencySymbol: 'G', locale: 'fr-HT' },
  { name: 'Honduras', code: 'HN', flag: '🇭🇳', currency: 'HNL', currencySymbol: 'L', locale: 'es-HN' },
  { name: 'Hungary', code: 'HU', flag: '🇭🇺', currency: 'HUF', currencySymbol: 'Ft', locale: 'hu-HU' },
  { name: 'Iceland', code: 'IS', flag: '🇮🇸', currency: 'ISK', currencySymbol: 'kr', locale: 'is-IS' },
  { name: 'India', code: 'IN', flag: '🇮🇳', currency: 'INR', currencySymbol: '₹', locale: 'en-IN' },
  { name: 'Indonesia', code: 'ID', flag: '🇮🇩', currency: 'IDR', currencySymbol: 'Rp', locale: 'id-ID' },
  { name: 'Iran', code: 'IR', flag: '🇮🇷', currency: 'IRR', currencySymbol: '﷼', locale: 'fa-IR' },
  { name: 'Iraq', code: 'IQ', flag: '🇮🇶', currency: 'IQD', currencySymbol: 'ع.د', locale: 'ar-IQ' },
  { name: 'Ireland', code: 'IE', flag: '🇮🇪', currency: 'EUR', currencySymbol: '€', locale: 'en-IE' },
  { name: 'Israel', code: 'IL', flag: '🇮🇱', currency: 'ILS', currencySymbol: '₪', locale: 'he-IL' },
  { name: 'Italy', code: 'IT', flag: '🇮🇹', currency: 'EUR', currencySymbol: '€', locale: 'it-IT' },
  { name: 'Ivory Coast', code: 'CI', flag: '🇨🇮', currency: 'XOF', currencySymbol: 'CFA', locale: 'fr-CI' },
  { name: 'Jamaica', code: 'JM', flag: '🇯🇲', currency: 'JMD', currencySymbol: 'J$', locale: 'en-JM' },
  { name: 'Japan', code: 'JP', flag: '🇯🇵', currency: 'JPY', currencySymbol: '¥', locale: 'ja-JP' },
  { name: 'Jordan', code: 'JO', flag: '🇯🇴', currency: 'JOD', currencySymbol: 'د.ا', locale: 'ar-JO' },
  { name: 'Kazakhstan', code: 'KZ', flag: '🇰🇿', currency: 'KZT', currencySymbol: '₸', locale: 'kk-KZ' },
  { name: 'Kenya', code: 'KE', flag: '🇰🇪', currency: 'KES', currencySymbol: 'Ksh', locale: 'sw-KE' },
  { name: 'Kiribati', code: 'KI', flag: '🇰🇮', currency: 'AUD', currencySymbol: 'A$', locale: 'en-KI' },
  { name: 'Kuwait', code: 'KW', flag: '🇰🇼', currency: 'KWD', currencySymbol: 'د.ك', locale: 'ar-KW' },
  { name: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬', currency: 'KGS', currencySymbol: 'с', locale: 'ky-KG' },
  { name: 'Laos', code: 'LA', flag: '🇱🇦', currency: 'LAK', currencySymbol: '₭', locale: 'lo-LA' },
  { name: 'Latvia', code: 'LV', flag: '🇱🇻', currency: 'EUR', currencySymbol: '€', locale: 'lv-LV' },
  { name: 'Lebanon', code: 'LB', flag: '🇱🇧', currency: 'LBP', currencySymbol: 'ل.ل', locale: 'ar-LB' },
  { name: 'Lesotho', code: 'LS', flag: '🇱🇸', currency: 'LSL', currencySymbol: 'L', locale: 'en-LS' },
  { name: 'Liberia', code: 'LR', flag: '🇱🇷', currency: 'LRD', currencySymbol: '$', locale: 'en-LR' },
  { name: 'Libya', code: 'LY', flag: '🇱🇾', currency: 'LYD', currencySymbol: 'ل.د', locale: 'ar-LY' },
  { name: 'Liechtenstein', code: 'LI', flag: '🇱🇮', currency: 'CHF', currencySymbol: 'CHF', locale: 'de-LI' },
  { name: 'Lithuania', code: 'LT', flag: '🇱🇹', currency: 'EUR', currencySymbol: '€', locale: 'lt-LT' },
  { name: 'Luxembourg', code: 'LU', flag: '🇱🇺', currency: 'EUR', currencySymbol: '€', locale: 'lb-LU' },
  { name: 'Madagascar', code: 'MG', flag: '🇲🇬', currency: 'MGA', currencySymbol: 'Ar', locale: 'mg-MG' },
  { name: 'Malawi', code: 'MW', flag: '🇲🇼', currency: 'MWK', currencySymbol: 'MK', locale: 'en-MW' },
  { name: 'Malaysia', code: 'MY', flag: '🇲🇾', currency: 'MYR', currencySymbol: 'RM', locale: 'ms-MY' },
  { name: 'Maldives', code: 'MV', flag: '🇲🇻', currency: 'MVR', currencySymbol: 'Rf', locale: 'dv-MV' },
  { name: 'Mali', code: 'ML', flag: '🇲🇱', currency: 'XOF', currencySymbol: 'CFA', locale: 'fr-ML' },
  { name: 'Malta', code: 'MT', flag: '🇲🇹', currency: 'EUR', currencySymbol: '€', locale: 'mt-MT' },
  { name: 'Marshall Islands', code: 'MH', flag: '🇲🇭', currency: 'USD', currencySymbol: '$', locale: 'en-MH' },
  { name: 'Mauritania', code: 'MR', flag: '🇲🇷', currency: 'MRU', currencySymbol: 'UM', locale: 'ar-MR' },
  { name: 'Mauritius', code: 'MU', flag: '🇲🇺', currency: 'MUR', currencySymbol: '₨', locale: 'en-MU' },
  { name: 'Mexico', code: 'MX', flag: '🇲🇽', currency: 'MXN', currencySymbol: '$', locale: 'es-MX' },
  { name: 'Micronesia', code: 'FM', flag: '🇫🇲', currency: 'USD', currencySymbol: '$', locale: 'en-FM' },
  { name: 'Moldova', code: 'MD', flag: '🇲🇩', currency: 'MDL', currencySymbol: 'L', locale: 'ro-MD' },
  { name: 'Monaco', code: 'MC', flag: '🇲🇨', currency: 'EUR', currencySymbol: '€', locale: 'fr-MC' },
  { name: 'Mongolia', code: 'MN', flag: '🇲🇳', currency: 'MNT', currencySymbol: '₮', locale: 'mn-MN' },
  { name: 'Montenegro', code: 'ME', flag: '🇲🇪', currency: 'EUR', currencySymbol: '€', locale: 'sr-ME' },
  { name: 'Morocco', code: 'MA', flag: '🇲🇦', currency: 'MAD', currencySymbol: 'د.م.', locale: 'ar-MA' },
  { name: 'Mozambique', code: 'MZ', flag: '🇲🇿', currency: 'MZN', currencySymbol: 'MT', locale: 'pt-MZ' },
  { name: 'Myanmar', code: 'MM', flag: '🇲🇲', currency: 'MMK', currencySymbol: 'K', locale: 'my-MM' },
  { name: 'Namibia', code: 'NA', flag: '🇳🇦', currency: 'NAD', currencySymbol: '$', locale: 'en-NA' },
  { name: 'Nauru', code: 'NR', flag: '🇳🇷', currency: 'AUD', currencySymbol: 'A$', locale: 'en-NR' },
  { name: 'Nepal', code: 'NP', flag: '🇳🇵', currency: 'NPR', currencySymbol: '₨', locale: 'ne-NP' },
  { name: 'Netherlands', code: 'NL', flag: '🇳🇱', currency: 'EUR', currencySymbol: '€', locale: 'nl-NL' },
  { name: 'New Zealand', code: 'NZ', flag: '🇳🇿', currency: 'NZD', currencySymbol: 'NZ$', locale: 'en-NZ' },
  { name: 'Nicaragua', code: 'NI', flag: '🇳🇮', currency: 'NIO', currencySymbol: 'C$', locale: 'es-NI' },
  { name: 'Niger', code: 'NE', flag: '🇳🇪', currency: 'XOF', currencySymbol: 'CFA', locale: 'fr-NE' },
  { name: 'Nigeria', code: 'NG', flag: '🇳🇬', currency: 'NGN', currencySymbol: '₦', locale: 'en-NG' },
  { name: 'North Korea', code: 'KP', flag: '🇰🇵', currency: 'KPW', currencySymbol: '₩', locale: 'ko-KP' },
  { name: 'North Macedonia', code: 'MK', flag: '🇲🇰', currency: 'MKD', currencySymbol: 'ден', locale: 'mk-MK' },
  { name: 'Norway', code: 'NO', flag: '🇳🇴', currency: 'NOK', currencySymbol: 'kr', locale: 'nb-NO' },
  { name: 'Oman', code: 'OM', flag: '🇴🇲', currency: 'OMR', currencySymbol: 'ر.ع.', locale: 'ar-OM' },
  { name: 'Pakistan', code: 'PK', flag: '🇵🇰', currency: 'PKR', currencySymbol: '₨', locale: 'ur-PK' },
  { name: 'Palau', code: 'PW', flag: '🇵🇼', currency: 'USD', currencySymbol: '$', locale: 'en-PW' },
  { name: 'Palestine', code: 'PS', flag: '🇵🇸', currency: 'ILS', currencySymbol: '₪', locale: 'ar-PS' },
  { name: 'Panama', code: 'PA', flag: '🇵🇦', currency: 'PAB', currencySymbol: 'B/.', locale: 'es-PA' },
  { name: 'Papua New Guinea', code: 'PG', flag: '🇵🇬', currency: 'PGK', currencySymbol: 'K', locale: 'en-PG' },
  { name: 'Paraguay', code: 'PY', flag: '🇵🇾', currency: 'PYG', currencySymbol: '₲', locale: 'es-PY' },
  { name: 'Peru', code: 'PE', flag: '🇵🇪', currency: 'PEN', currencySymbol: 'S/.', locale: 'es-PE' },
  { name: 'Philippines', code: 'PH', flag: '🇵🇭', currency: 'PHP', currencySymbol: '₱', locale: 'en-PH' },
  { name: 'Poland', code: 'PL', flag: '🇵🇱', currency: 'PLN', currencySymbol: 'zł', locale: 'pl-PL' },
  { name: 'Portugal', code: 'PT', flag: '🇵🇹', currency: 'EUR', currencySymbol: '€', locale: 'pt-PT' },
  { name: 'Qatar', code: 'QA', flag: '🇶🇦', currency: 'QAR', currencySymbol: 'ر.ق', locale: 'ar-QA' },
  { name: 'Romania', code: 'RO', flag: '🇷🇴', currency: 'RON', currencySymbol: 'lei', locale: 'ro-RO' },
  { name: 'Russia', code: 'RU', flag: '🇷🇺', currency: 'RUB', currencySymbol: '₽', locale: 'ru-RU' },
  { name: 'Rwanda', code: 'RW', flag: '🇷🇼', currency: 'RWF', currencySymbol: 'Fr', locale: 'rw-RW' },
  { name: 'Saint Kitts and Nevis', code: 'KN', flag: '🇰🇳', currency: 'XCD', currencySymbol: '$', locale: 'en-KN' },
  { name: 'Saint Lucia', code: 'LC', flag: '🇱🇨', currency: 'XCD', currencySymbol: '$', locale: 'en-LC' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', flag: '🇻🇨', currency: 'XCD', currencySymbol: '$', locale: 'en-VC' },
  { name: 'Samoa', code: 'WS', flag: '🇼🇸', currency: 'WST', currencySymbol: 'T', locale: 'sm-WS' },
  { name: 'San Marino', code: 'SM', flag: '🇸🇲', currency: 'EUR', currencySymbol: '€', locale: 'it-SM' },
  { name: 'Sao Tome and Principe', code: 'ST', flag: '🇸🇹', currency: 'STN', currencySymbol: 'Db', locale: 'pt-ST' },
  { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦', currency: 'SAR', currencySymbol: 'ر.س', locale: 'ar-SA' },
  { name: 'Senegal', code: 'SN', flag: '🇸🇳', currency: 'XOF', currencySymbol: 'CFA', locale: 'fr-SN' },
  { name: 'Serbia', code: 'RS', flag: '🇷🇸', currency: 'RSD', currencySymbol: 'din', locale: 'sr-RS' },
  { name: 'Seychelles', code: 'SC', flag: '🇸🇨', currency: 'SCR', currencySymbol: '₨', locale: 'en-SC' },
  { name: 'Sierra Leone', code: 'SL', flag: '🇸🇱', currency: 'SLL', currencySymbol: 'Le', locale: 'en-SL' },
  { name: 'Singapore', code: 'SG', flag: '🇸🇬', currency: 'SGD', currencySymbol: 'S$', locale: 'en-SG' },
  { name: 'Slovakia', code: 'SK', flag: '🇸🇰', currency: 'EUR', currencySymbol: '€', locale: 'sk-SK' },
  { name: 'Slovenia', code: 'SI', flag: '🇸🇮', currency: 'EUR', currencySymbol: '€', locale: 'sl-SI' },
  { name: 'Solomon Islands', code: 'SB', flag: '🇸🇧', currency: 'SBD', currencySymbol: '$', locale: 'en-SB' },
  { name: 'Somalia', code: 'SO', flag: '🇸🇴', currency: 'SOS', currencySymbol: 'Sh', locale: 'so-SO' },
  { name: 'South Africa', code: 'ZA', flag: '🇿🇦', currency: 'ZAR', currencySymbol: 'R', locale: 'en-ZA' },
  { name: 'South Korea', code: 'KR', flag: '🇰🇷', currency: 'KRW', currencySymbol: '₩', locale: 'ko-KR' },
  { name: 'South Sudan', code: 'SS', flag: '🇸🇸', currency: 'SSP', currencySymbol: '£', locale: 'en-SS' },
  { name: 'Spain', code: 'ES', flag: '🇪🇸', currency: 'EUR', currencySymbol: '€', locale: 'es-ES' },
  { name: 'Sri Lanka', code: 'LK', flag: '🇱🇰', currency: 'LKR', currencySymbol: '₨', locale: 'si-LK' },
  { name: 'Sudan', code: 'SD', flag: '🇸🇩', currency: 'SDG', currencySymbol: 'ج.س', locale: 'ar-SD' },
  { name: 'Suriname', code: 'SR', flag: '🇸🇷', currency: 'SRD', currencySymbol: '$', locale: 'nl-SR' },
  { name: 'Sweden', code: 'SE', flag: '🇸🇪', currency: 'SEK', currencySymbol: 'kr', locale: 'sv-SE' },
  { name: 'Switzerland', code: 'CH', flag: '🇨🇭', currency: 'CHF', currencySymbol: 'CHF', locale: 'de-CH' },
  { name: 'Syria', code: 'SY', flag: '🇸🇾', currency: 'SYP', currencySymbol: '£', locale: 'ar-SY' },
  { name: 'Taiwan', code: 'TW', flag: '🇹🇼', currency: 'TWD', currencySymbol: 'NT$', locale: 'zh-TW' },
  { name: 'Tajikistan', code: 'TJ', flag: '🇹🇯', currency: 'TJS', currencySymbol: 'SM', locale: 'tg-TJ' },
  { name: 'Tanzania', code: 'TZ', flag: '🇹🇿', currency: 'TZS', currencySymbol: 'Sh', locale: 'sw-TZ' },
  { name: 'Thailand', code: 'TH', flag: '🇹🇭', currency: 'THB', currencySymbol: '฿', locale: 'th-TH' },
  { name: 'Timor-Leste', code: 'TL', flag: '🇹🇱', currency: 'USD', currencySymbol: '$', locale: 'pt-TL' },
  { name: 'Togo', code: 'TG', flag: '🇹🇬', currency: 'XOF', currencySymbol: 'CFA', locale: 'fr-TG' },
  { name: 'Tonga', code: 'TO', flag: '🇹🇴', currency: 'TOP', currencySymbol: 'T$', locale: 'to-TO' },
  { name: 'Trinidad and Tobago', code: 'TT', flag: '🇹🇹', currency: 'TTD', currencySymbol: 'TT$', locale: 'en-TT' },
  { name: 'Tunisia', code: 'TN', flag: '🇹🇳', currency: 'TND', currencySymbol: 'د.ت', locale: 'ar-TN' },
  { name: 'Turkey', code: 'TR', flag: '🇹🇷', currency: 'TRY', currencySymbol: '₺', locale: 'tr-TR' },
  { name: 'Turkmenistan', code: 'TM', flag: '🇹🇲', currency: 'TMT', currencySymbol: 'T', locale: 'tk-TM' },
  { name: 'Tuvalu', code: 'TV', flag: '🇹🇻', currency: 'AUD', currencySymbol: 'A$', locale: 'en-TV' },
  { name: 'Uganda', code: 'UG', flag: '🇺🇬', currency: 'UGX', currencySymbol: 'Sh', locale: 'sw-UG' },
  { name: 'Ukraine', code: 'UA', flag: '🇺🇦', currency: 'UAH', currencySymbol: '₴', locale: 'uk-UA' },
  { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪', currency: 'AED', currencySymbol: 'د.إ', locale: 'ar-AE' },
  { name: 'United Kingdom', code: 'GB', flag: '🇬🇧', currency: 'GBP', currencySymbol: '£', locale: 'en-GB' },
  { name: 'United States', code: 'US', flag: '🇺🇸', currency: 'USD', currencySymbol: '$', locale: 'en-US' },
  { name: 'Uruguay', code: 'UY', flag: '🇺🇾', currency: 'UYU', currencySymbol: '$U', locale: 'es-UY' },
  { name: 'Uzbekistan', code: 'UZ', flag: '🇺🇿', currency: 'UZS', currencySymbol: 'лв', locale: 'uz-UZ' },
  { name: 'Vanuatu', code: 'VU', flag: '🇻🇺', currency: 'VUV', currencySymbol: 'Vt', locale: 'bi-VU' },
  { name: 'Vatican City', code: 'VA', flag: '🇻🇦', currency: 'EUR', currencySymbol: '€', locale: 'it-VA' },
  { name: 'Venezuela', code: 'VE', flag: '🇻🇪', currency: 'VES', currencySymbol: 'Bs.S', locale: 'es-VE' },
  { name: 'Vietnam', code: 'VN', flag: '🇻🇳', currency: 'VND', currencySymbol: '₫', locale: 'vi-VN' },
  { name: 'Yemen', code: 'YE', flag: '🇾🇪', currency: 'YER', currencySymbol: '﷼', locale: 'ar-YE' },
  { name: 'Zambia', code: 'ZM', flag: '🇿🇲', currency: 'ZMW', currencySymbol: 'ZK', locale: 'en-ZM' },
  { name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼', currency: 'ZWL', currencySymbol: '$', locale: 'en-ZW' },
];

/**
 * Common currencies list for the currency picker.
 */
export const CURRENCIES = [
  { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  { code: 'MXN', symbol: '$', name: 'Mexican Peso' },
  { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
  { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc' },
  { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
  { code: 'SEK', symbol: 'kr', name: 'Swedish Krona' },
  { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone' },
  { code: 'DKK', symbol: 'kr', name: 'Danish Krone' },
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' },
  { code: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal' },
  { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal' },
  { code: 'TRY', symbol: '₺', name: 'Turkish Lira' },
  { code: 'RUB', symbol: '₽', name: 'Russian Ruble' },
  { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  { code: 'THB', symbol: '฿', name: 'Thai Baht' },
  { code: 'PHP', symbol: '₱', name: 'Philippine Peso' },
  { code: 'PLN', symbol: 'zł', name: 'Polish Zloty' },
  { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint' },
  { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna' },
  { code: 'ILS', symbol: '₪', name: 'Israeli Shekel' },
  { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound' },
  { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
  { code: 'KES', symbol: 'Ksh', name: 'Kenyan Shilling' },
  { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee' },
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
  { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia' },
  { code: 'VND', symbol: '₫', name: 'Vietnamese Dong' },
  { code: 'TWD', symbol: 'NT$', name: 'Taiwan Dollar' },
  { code: 'ARS', symbol: '$', name: 'Argentine Peso' },
  { code: 'COP', symbol: '$', name: 'Colombian Peso' },
  { code: 'CLP', symbol: '$', name: 'Chilean Peso' },
  { code: 'PEN', symbol: 'S/.', name: 'Peruvian Sol' },
  { code: 'RON', symbol: 'lei', name: 'Romanian Leu' },
  { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev' },
  { code: 'HRK', symbol: 'kn', name: 'Croatian Kuna' },
  { code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi' },
  { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge' },
  { code: 'GEL', symbol: '₾', name: 'Georgian Lari' },
  { code: 'LKR', symbol: '₨', name: 'Sri Lankan Rupee' },
];

/**
 * Get country by code.
 * @param {string} code - ISO 3166-1 alpha-2 country code
 */
export function getCountryByCode(code) {
  return COUNTRIES.find((c) => c.code === code);
}

/**
 * Get currency info by code.
 * @param {string} code - ISO 4217 currency code
 */
export function getCurrencyByCode(code) {
  return CURRENCIES.find((c) => c.code === code);
}

export default COUNTRIES;
