/**
 * FinTrack Pro — Transaction Schema v2
 * Reference object describing the shape of every transaction record.
 * Used for validation, form generation, and documentation.
 */

/**
 * @typedef {Object} RecurringRule
 * @property {'daily'|'weekly'|'monthly'|'quarterly'|'yearly'|'custom'} frequency
 * @property {number} interval         - e.g. every 2 weeks
 * @property {number|null} dayOfMonth
 * @property {string|null} endDate     - ISO 8601 date
 * @property {number|null} maxOccurrences
 */

/**
 * @typedef {Object} SplitPart
 * @property {string} category
 * @property {number} amount
 * @property {string} notes
 */

/**
 * @typedef {Object} Transaction
 * @property {string}  id
 * @property {string}  profileId
 * @property {string}  date              - ISO 8601: YYYY-MM-DD
 * @property {string}  description
 * @property {number}  amount            - always positive
 * @property {string}  currency          - e.g. 'INR'
 * @property {number}  convertedAmount   - in base currency
 * @property {string}  baseCurrency
 * @property {string}  category
 * @property {string}  subcategory
 * @property {'income'|'expense'|'transfer'} type
 * @property {string}  accountId
 * @property {string|null} toAccountId  - for transfers
 * @property {string[]} tags
 * @property {string}  notes
 * @property {string|null} receiptImage - base64 encoded
 * @property {boolean} isRecurring
 * @property {string|null} recurringId
 * @property {RecurringRule|null} recurringRule
 * @property {'upi'|'neft'|'imps'|'cash'|'card'|'cheque'|'rtgs'|'other'} paymentMethod
 * @property {string}  merchant
 * @property {string}  utrNumber        - for UPI/NEFT transactions
 * @property {string}  refNumber
 * @property {'manual'|'csv'|'pdf'|'ofx'|'xlsx'} importedFrom
 * @property {string}  bankRef
 * @property {boolean} isSplit
 * @property {SplitPart[]|null} splitParts
 * @property {string|null} projectId    - Corporate Individual only
 * @property {string|null} clientId     - Corporate Individual only
 * @property {boolean} isBillable       - Corporate Individual only
 * @property {0|5|12|18|28|null} gstRate - Corporate Individual only
 * @property {number|null} gstAmount    - Corporate Individual only
 * @property {boolean} [isAutoGenerated] - set by recurring engine
 * @property {string}  createdAt        - ISO 8601
 * @property {string}  updatedAt        - ISO 8601
 */

/** Canonical schema shape — used as reference & for validation defaults */
export const TRANSACTION_SCHEMA = {
  id: '',
  profileId: '',
  date: '',               // ISO 8601: YYYY-MM-DD
  description: '',
  amount: 0,              // always positive
  currency: 'INR',
  convertedAmount: 0,     // in base currency
  baseCurrency: 'INR',
  category: '',
  subcategory: '',
  type: 'expense',        // 'income' | 'expense' | 'transfer'
  accountId: '',
  toAccountId: null,      // for transfers
  tags: [],
  notes: '',
  receiptImage: null,     // base64
  isRecurring: false,
  recurringId: null,
  recurringRule: null,    // { frequency, interval, dayOfMonth, endDate, maxOccurrences }
  paymentMethod: 'other', // 'upi'|'neft'|'imps'|'cash'|'card'|'cheque'|'rtgs'|'other'
  merchant: '',
  utrNumber: '',          // for UPI/NEFT transactions
  refNumber: '',
  importedFrom: 'manual', // 'manual'|'csv'|'pdf'|'ofx'|'xlsx'
  bankRef: '',
  isSplit: false,
  splitParts: null,       // [{ category, amount, notes }]
  // Corporate Individual only:
  projectId: null,
  clientId: null,
  isBillable: false,
  gstRate: null,          // 0, 5, 12, 18, 28
  gstAmount: null,
  isAutoGenerated: false,
  createdAt: '',
  updatedAt: '',
};

/** Valid transaction types */
export const TRANSACTION_TYPES = ['income', 'expense', 'transfer'];

/** Valid payment methods */
export const PAYMENT_METHODS = ['upi', 'neft', 'imps', 'cash', 'card', 'cheque', 'rtgs', 'other'];

/** Valid import sources */
export const IMPORT_SOURCES = ['manual', 'csv', 'pdf', 'ofx', 'xlsx'];

/** Valid recurring frequencies */
export const RECURRING_FREQUENCIES = ['daily', 'weekly', 'monthly', 'quarterly', 'yearly', 'custom'];

/** Valid GST rates (India) */
export const GST_RATES = [0, 5, 12, 18, 28];

/**
 * Validate a transaction object against the schema.
 * Returns an array of validation error strings (empty = valid).
 * @param {Partial<Transaction>} tx
 * @returns {string[]}
 */
export function validateTransaction(tx) {
  const errors = [];

  if (!tx.description || tx.description.trim() === '') {
    errors.push('Description is required');
  }
  if (typeof tx.amount !== 'number' || tx.amount <= 0) {
    errors.push('Amount must be a positive number');
  }
  if (!tx.date || !/^\d{4}-\d{2}-\d{2}$/.test(tx.date)) {
    errors.push('Date must be in YYYY-MM-DD format');
  }
  if (!TRANSACTION_TYPES.includes(tx.type)) {
    errors.push(`Type must be one of: ${TRANSACTION_TYPES.join(', ')}`);
  }
  if (!tx.accountId) {
    errors.push('Account is required');
  }
  if (tx.type === 'transfer' && !tx.toAccountId) {
    errors.push('Destination account is required for transfers');
  }
  if (tx.type === 'transfer' && tx.accountId === tx.toAccountId) {
    errors.push('Source and destination accounts must differ for transfers');
  }
  if (tx.paymentMethod && !PAYMENT_METHODS.includes(tx.paymentMethod)) {
    errors.push(`Payment method must be one of: ${PAYMENT_METHODS.join(', ')}`);
  }
  if (tx.isSplit && (!Array.isArray(tx.splitParts) || tx.splitParts.length < 2)) {
    errors.push('Split transactions require at least 2 parts');
  }
  if (tx.isSplit && Array.isArray(tx.splitParts)) {
    const splitTotal = tx.splitParts.reduce((sum, p) => sum + (p.amount || 0), 0);
    if (Math.abs(splitTotal - tx.amount) > 0.01) {
      errors.push(`Split parts total (${splitTotal}) must equal transaction amount (${tx.amount})`);
    }
  }
  if (tx.gstRate !== null && tx.gstRate !== undefined && !GST_RATES.includes(tx.gstRate)) {
    errors.push(`GST rate must be one of: ${GST_RATES.join(', ')}`);
  }

  return errors;
}

/**
 * Create a minimal transaction with all defaults applied.
 * @param {Partial<Transaction>} overrides
 * @returns {Transaction}
 */
export function createTransactionDefaults(overrides = {}) {
  const now = new Date().toISOString();
  const today = now.slice(0, 10);
  return {
    ...TRANSACTION_SCHEMA,
    id: crypto.randomUUID(),
    date: today,
    createdAt: now,
    updatedAt: now,
    ...overrides,
  };
}

export default TRANSACTION_SCHEMA;
